spring:
  application:
    name: yupao-backend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: a3181389202
    url: jdbc:mysql://localhost:3306/user_center
  # session过期时间
  session:
    timeout: 86400

server:
  port: 8080
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值